- hosts: FW00
  collections: '[fortinet.fortios]'
  connection: httpapi
  vars:
    vdom: root
    ansible_httpapi_use_ssl: 'no'
    ansible_httpapi_validate_certs: 'no'
    ansible_httpapi_port: '80'
    ansible_network_os: fortinet.fortios.fortios
  tasks:
  - name: Configure url to be filtered by fortigate
    fortios_webfilter_urlfilter:
      vdom: '{{ vdom }}'
      access_token: 6kyx54wpbpp8q5GHGktrN4fpj5jsnq
      state: present
      webfilter_urlfilter:
        id: '351'
        name: poopy20
        entries:
        - action: allow
          dns_address_family: ipv4
          id: '1'
          referrer_host: myhostname
          status: enable
          type: simple
          url: microsoft.com
        - action: allow
          dns_address_family: ipv4
          id: '2'
          referrer_host: myhostname
          status: enable
          type: simple
          url: wikipedia.org
        - action: allow
          dns_address_family: ipv4
          id: '3'
          referrer_host: myhostname
          status: enable
          type: simple
          url: support.apple.com
        - action: allow
          dns_address_family: ipv4
          id: '4'
          referrer_host: myhostname
          status: enable
          type: simple
          url: tmz.com
        - action: allow
          dns_address_family: ipv4
          id: '5'
          referrer_host: myhostname
          status: enable
          type: simple
          url: bankofamerica.com
        - action: allow
          dns_address_family: ipv4
          id: '6'
          referrer_host: myhostname
          status: enable
          type: simple
          url: www.bankofamerica.com
        - action: allow
          dns_address_family: ipv4
          id: '7'
          referrer_host: myhostname
          status: enable
          type: simple
          url: www.usbank.com
        - action: allow
          dns_address_family: ipv4
          id: '8'
          referrer_host: myhostname
          status: enable
          type: simple
          url: eastsideboxing.com
        - action: allow
          dns_address_family: ipv4
          id: '9'
          referrer_host: myhostname
          status: enable
          type: simple
          url: nextdoor.com
        - action: allow
          dns_address_family: ipv4
          id: '10'
          referrer_host: myhostname
          status: enable
          type: simple
          url: legalhelp.com
        - action: block
          dns_address_family: ipv4
          id: '11'
          referrer_host: myhostname
          status: enable
          type: wildcard
          url: '*'
